@accessToken = QWxpZWYgU2F0dQ==
### POST Withdrawal Balance
POST http://localhost:8000/api/v1/withdrawal
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "amount" : 500,
    "order_id": "1",
    "timestamp": "{{$timestamp}}"
}